### ISSUE TITLE
Filter

### ISSUE THREAD

**Issue by Weezer15** [lylk/nara#1]
I bought the filter app for my computer to add cool affects to my photography but I can't access anything on the app I paid money for it and what I can access it might as well have been free theres no other windows popping up to do black and white pictures or any other of the like I can't do much and I'm rather dissapointed that I paid money for an app that doesn't do anything theres not instructions on how to get around the app If I could receive feedback on step by step instructions on how to navigate the app and figure out how it works I will probably keep it if not I just wasted my money. Thanks to anyone who can help.

**Comment by lylk** [comment]
Look carefully software introduction , and then make sure the operating system 10.9 or more!

**Comment by lylk** [comment]
Double-click on the picture to open the imageEdit panel!
