### ISSUE TITLE
Does not fully uninstall software

### ISSUE THREAD

**Issue by jawsmith** [lylk/nara#3]
I went back through, because I had a problem, and the software I uninstalled was still there!  I was surprised that it had not fully uninstalled the item and did not let me know what parts were still there.  A simple "find" command produced more than a dozen entries of the software that was uninstalled.  No "sudo", just "find" in the Users/jawsmith folder.  What a piece of crap software.  Needless to say, I had to go through manually and delete all the entries, one by one... I was not happy.  I would really like a better piece of software or a refund!

**Comment by lylk** [comment]
All uninstallers of app store must support sandbox. so some files can not delete. you need manual remove.
